version: "3.8"

services: 
    graphql_node:
        container_name: graphql_node
        image: node:12.14.1
        working_dir: /app
        volumes:
            - ./:/app
        depends_on:
            - graphql_mongo
        ports: 
            - 8000:8000
    graphql_mongo:
        container_name: graphql_mongo
        image: mongo:4.2.2
        expose:
            - 27017
        ports: 
            - 27030:27017
        volumes:
            -  ~/data/db/graphql:/data/db